name: minishop
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.3+1
  url_launcher: ^6.2.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
  - assets/images/noibat.png
  - assets/images/logo.png
  - assets/images/dientu.png
  - assets/images/thoitrang.png
  - assets/images/mypham.png
  - assets/images/giadung.png
  - assets/images/doisong.png
  - assets/images/dochoi.png
  - assets/images/thethao.png
  - assets/images/thucpham.png
